FROM centos:centos7
MAINTAINER kinghu

ADD ./apache-tomcat-9.0.2.tar.gz /root
ADD ./jdk-8u65-linux-x64.tar.gz /root


ENV JAVA_HOME /root/jdk1.8.0_65
ENV CATALINA_HOME /root/apache-tomcat-9.0.2
ENV PATH $PATH:$JAVA_HOME/bin:$CATALINA_HOME/bin
VOLUME /root/apache-tomcat-9.0.2/webapps

EXPOSE 8080

CMD ["/root/apache-tomcat-9.0.2/bin/catalina.sh","run"]